# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mxmJ3AbVbcXIs_UYaQTOEJeDFwKTvTwv
"""

import numpy as np

students = {
    "Anandh": [23, 50, 57, 99],
    "Arjavi": [22, 45, 65, 34],
    "Pratham": [44, 64, 45, 76],
    "isha": [34, 26, 98, 54],
    "indu": [46, 78, 43, 56]
}

print("="*40)
print("      Students Report Card")
print("="*40)

for student, marks in students.items():
    average = np.mean(marks)

    if average >= 90:
        grade = "A"
    elif average >= 75:
        grade = "B"
    elif average >= 60:
        grade = "C"
    elif average >= 50:
        grade = "D"
    else:
        grade = "F"

    if average >= 50:
        status = "PASS"
    else:
        status = "FAIL"

    print(f"\nStudent: {student}")
    print(f"Average: {average:.2f}")
    print(f"Grade: {grade}")
    print(f"Status: {status}")

print("\n" + "="*40)

